config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
end



# Rails.application.routes.draw do
#   resources :cocktails, only: [:show, :new, :create] do
#     resources :doses, only: [:new, :create]
#   end
#   resources :doses, only: :destroy
#   root to: "cocktails#index"
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence:true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end



  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.create(dose_params)

    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      redirect_to cocktail_path(@cocktail)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/views/cocktails/edit.html.erb
<h1>Cocktail#edit</h1>
<p>Find me in app/views/cocktail/edit.html.erb</p>

app/views/cocktails/index.html.erb
<html>
  <head>
    <title>Cocktails</title>

    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="DPyVVHMIbjEuasKWkBxZidk20K+P/vPgrdu+oZpY6KFUvfh54UuTtcMzd1mVC/trh4jb586A+X1COw5bxvyPpw==" />


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" media="all" href="/assets/application-fb2688522f27ef5dc4a80b713dca32773a83e3c9c2533473c0daa507bca1544b.css" data-turbolinks-track="reload" />
    <script src="/assets/application-e8cad604caacf8b819d144d3c75378ac96806728fb7d5e41f239c29e65492a33.js" data-turbolinks-track="reload"></script>
  </head>


<ul id="navbar">
    <li class="active"><a href="#">Home</a></li>
    <li><%= link_to "New🍸", new_cocktail_path %></li>
    <li><%= link_to "Custom", new_cocktail_path %></li>
</ul>
</ul>


<div class="banner">
  <div class="banner-content">
    <h1>Cocktails delivered wherever you are !🍸 </h1>
    <p> 🍸 </p>
    <a class=><%= link_to "Mix a new cocktail", new_cocktail_path, class: "btn btn-primary" %></a>
  </div>
</div>
<br>
</br>

<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>Delivered</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>Delivered</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>Delivered</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>Delivered</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
      </div>
</div>

<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>anywhere</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>anywhere</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>anywhere</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
<div class="flip-container">
          <div class="flip3D">
            <div class="back" ><h3>anywhere</h3></div>
            <div class="front" ><h3>Drinks </h3></div>
          </div>
        </div>
      </div>
</div>



<!-- <div class="container">
  <!-- <div class="cocktails"> -->
<!-- <h2 id="demo02">2. Your menu 🍸 </h2> -->
<!-- <div class="hover02 column">
  <div>
    <figure><img src="https://images.unsplash.com/photo-1531387367216-681093c0279b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjF9&s=a7bc51239cbf027bba03230e4a92efcc&auto=format&fit=crop&w=1016&q=80" /></figure>

  </div> -->

 <!--  <% @cocktails.each do |cocktail| %>
      <div class="cocktail">
        <p> <%= link_to cocktail.name, cocktail_path(cocktail.id) %> </p>
      </div>
    <% end %>
  </div> -->



<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made by Andy Levis <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>
</div>

app/views/cocktails/new.html.erb
<ul id="navbar">
    <li class="active"><a href="#">press</a></li>
    <li><%= link_to "back", new_cocktail_path %></li>

</ul>


<div class="banner-new">
  <div class="banner-content">
    <h1>Order your cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>
</div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made by Andy Levis <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/cocktails/show.html.erb
<ul id="navbar">
    <li class="active"><a href="#">Home</a></li>
    <!-- <li><%= link_to "New🍸", new_cocktail_path %></li> -->
</ul>


<div class="banner-show">
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>

  <h3>Add ingredients</h3>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add", class: "btn btn-primary"%>
  <% end %>



    <% @cocktail.doses.each do |dose| %>
      <div class="ingredient">
        <p><%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to "Remove", cocktail_dose_path(dose.id), method: :delete %>
        </p>
      </div>
    <% end %>

</div>
</div>




  </div>
  <%= link_to "its on its way !", cocktails_path, class: "btn btn-primary" %>
</div>

app/views/dose/create.html.erb
<h1>Dose#create</h1>
<p>Find me in app/views/dose/create.html.erb</p>

app/views/dose/destroy.html.erb
<h1>Dose#destroy</h1>
<p>Find me in app/views/dose/destroy.html.erb</p>

app/views/dose/new.html.erb
<h1>Dose#new</h1>
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>RailsMisterCocktail</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>